### ISSUE TITLE
Kernel not starting on EKS

### ISSUE THREAD

**Issue by JulianWgs** [dask/helm-chart#52] opened 2020-04-24 07:56 UTC
Hello,

 I deployed this EKS cluster with eksctl:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster-01
  region: eu-central-1
  version: "1.14"

availabilityZones: ["eu-central-1a", "eu-central-1b","eu-central-1c"]

nodeGroups:
  - name: test-nodes
    instanceType: c5.large
    volumeSize: 30
    desiredCapacity: 2
    privateNetworking: true
    maxPodsPerNode: 10
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
```

and then I installed dask via helm on the cluster. I've only changed the the passwort in the configuration file.

CHART: dask-4.1.6
APP VERSION: 2.11.0

I can connect to the jupyter lab, create a notebook, save it, but no kernel is able to start (no execution or syntax highlighting).

I'd be glad for any help :)

**Comment by JulianWgs** [comment] 2020-04-27 08:51
I fixed the problem by port-forwarding the service:

`kubectl port-forward --namespace default svc/dask-jupyter 8011:80`
`kubectl port-forward --namespace default svc/dask-scheduler 8012:80`

See also #53 

Before closing this issue, I'd like to know if somebody else can replicate this behavior on EKS.

**Comment by jacobtomlinson** [comment] 2020-05-18 11:16
I am unable to reproduce.

Steps:
- `eksctl create cluster -f cluster.yml` using your cluster example from above
- `helm repo add dask https://helm.dask.org/ && helm repo update`
- `helm install test-dask dask/dask`
- `kubectl get svc` to find the loadbalancer address for the notebook
- Create a new notebook and run a test cell

![image](https://user-images.githubusercontent.com/1610850/82207230-6662f600-9901-11ea-947f-ad5a8288637e.png)

**Comment by consideRatio** [comment] 2020-11-06 16:18
@JulianWgs kubect port-forward will allow your computer that runs that command get a path towards a k8s service, but the LoadBalancer is a public entrypoint and we must aim for that rather than going with `kubectl port-forward` which only setup a local temporary network path.

Since this is not reproduced in may, I suggest to close this issue.

**Closed** 2020-11-06 16:20 UTC
