### ISSUE TITLE
Automatic updates have broken

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/helm-chart#308] opened 2022-08-12 14:57 UTC
There have been no CI generated updates here for a while. The current dask image is on version `2022.6.1` but `2022.8.0` is available.

The watch dependencies action seems to see this and try and make the change, but nothing is happening and the PR isn't getting opened.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/1610850/184382528-a6b45204-a5b2-4bee-9727-3a32da38472f.png">

https://github.com/dask/helm-chart/runs/7808534699?check_suite_focus=true

**Comment by consideRatio** [comment] 2022-08-12 15:16
I trust `git diff` not reporting something to be correct - that nothing is changed when using the gha-find-replace action.

Can I replace it with a straight forward replace operation I better understand and can debug directly in this repo? I find it hard to debug this overall and the use of an action for this is adding more complexity than it resolves.

**Comment by consideRatio** [comment] 2022-08-12 15:21
I suspect the issue is that the `include` statement is incorrect. It is not documented what kind of expression one can use in the include statement though.

**Comment by consideRatio** [comment] 2022-08-12 15:51
Attempt in #309 failed =/

I'll replace this action, its too much work to learn and debug this than just use `sed` that I can debug in a bash terminal quickly.

**Comment by jacobtomlinson** [comment] 2022-08-12 15:56
Thanks for looking at this @consideRatio. I think this was broken by https://github.com/dask/helm-chart/pull/248.

A quick fix would be to revert that. However you are in the process of replacing with `sed` that is fine too.

**Comment by consideRatio** [comment] 2022-08-12 16:09
I think it was broken by #248 (`regex` input default value changed), but then fixed again in #276 (set `regex: false` to retain previous version's behavior), but then broken again in #305 (invalid glob pattern guessed), and then failed to be fixed in #309 (not sure whats wrong), and now replaced with `sed` in #310 together with an action to read information from a Chart.yaml file.

**Closed** 2022-08-12 16:17 UTC
Labels: bug
